### ISSUE TITLE
added Groq

### ISSUE THREAD

**Issue by dalijon-byte** [john-adeojo/use-tools#1]
Thank you man @john-adeojo, here is the updated models for using GROQs llama3-70b-8192 and the minimal requirements.txt
just add: GROQ_API_KEY: 'YOUR__GROQ_KEY' into config.yaml
You've done everything nice. Thanks! 

USAGE in agent:
from models.groq_models import GroqModel
.... into your main
    # Uncoment below to run with GroqAI
    model_service = GroqModel
    model_name = 'llama3-70b-8192'
    stop = None

i am working on enabling LM

Works as good as gpt-4o!

[groq_models.zip](https://github.com/user-attachments/files/15871734/groq_models.zip)
[requirements.txt](https://github.com/user-attachments/files/15871777/requirements.txt)

**Comment by DeanChugall** [comment]
Hi @dalijon-byte 

To streamline the process and make it easier for everyone to review and integrate the changes, could you please create a pull request with the updated models and requirements instead of adding them to the issue?

Thanks.

**Comment by dalijon-byte** [comment]
@DeanChugall si mi dobar? ;) 
alright - pull requested - 
closing this one. best
